// Generated from prboom2/data/CMakeLists.txt.
// Order is load-bearing: rd_main.c is a stateful parser where each -switch
// sets a mode consumed by every following bare argument. Do not sort or glob
// (prboom2/data/lumps/ holds 33 .lmp files but only 29 belong in the wad).

pub const palette = [_][]const u8{
    "palette.rgb",
};

pub const lumps = [_][]const u8{
    "lumps/switches.lmp",
    "lumps/animated.lmp",
    "lumps/sndcurve.lmp",
    "lumps/soundfont/sndfont.lmp",
    "lumps/dsdacr.lmp",
    "lumps/dsdahud.lmp",
    "lumps/dsdatc.lmp",
};

pub const colormaps = [_][]const u8{
    "lumps/watermap.lmp",
};

pub const tables = [_][]const u8{
    "lumps/sinetabl.lmp",
    "lumps/tangtabl.lmp",
    "lumps/tantoang.lmp",
    "lumps/gammatbl.lmp",
    "lumps/chexdeh.lmp",
    "lumps/bfgbex.lmp",
    "lumps/nervebex.lmp",
    "lumps/glshadow.lmp",
    "lumps/gls_main.lmp",
    "lumps/gls_fuzz.lmp",
    "lumps/gls_v.lmp",
    "lumps/m_ammo.lmp",
    "lumps/m_armour.lmp",
    "lumps/m_arrow.lmp",
    "lumps/m_health.lmp",
    "lumps/m_key.lmp",
    "lumps/m_normal.lmp",
    "lumps/m_shadow.lmp",
    "lumps/m_power.lmp",
    "lumps/m_weap.lmp",
    "lumps/m_mark.lmp",
};

pub const sounds = [_][]const u8{
    "sounds/dsdgsit.wav",
    "sounds/dsdgatk.wav",
    "sounds/dsdgact.wav",
    "sounds/dsdgdth.wav",
    "sounds/dsdgpain.wav",
    "sounds/dssecret.wav",
};

pub const graphics = [_][]const u8{
    "graphics/dig033.ppm",
    "graphics/dig034.ppm",
    "graphics/dig035.ppm",
    "graphics/dig036.ppm",
    "graphics/dig037.ppm",
    "graphics/dig038.ppm",
    "graphics/dig039.ppm",
    "graphics/dig040.ppm",
    "graphics/dig041.ppm",
    "graphics/dig042.ppm",
    "graphics/dig043.ppm",
    "graphics/dig044.ppm",
    "graphics/dig045.ppm",
    "graphics/dig046.ppm",
    "graphics/dig047.ppm",
    "graphics/dig048.ppm",
    "graphics/dig049.ppm",
    "graphics/dig050.ppm",
    "graphics/dig051.ppm",
    "graphics/dig052.ppm",
    "graphics/dig053.ppm",
    "graphics/dig054.ppm",
    "graphics/dig055.ppm",
    "graphics/dig056.ppm",
    "graphics/dig057.ppm",
    "graphics/dig058.ppm",
    "graphics/dig059.ppm",
    "graphics/dig060.ppm",
    "graphics/dig061.ppm",
    "graphics/dig062.ppm",
    "graphics/dig063.ppm",
    "graphics/dig064.ppm",
    "graphics/dig065.ppm",
    "graphics/dig066.ppm",
    "graphics/dig067.ppm",
    "graphics/dig068.ppm",
    "graphics/dig069.ppm",
    "graphics/dig070.ppm",
    "graphics/dig071.ppm",
    "graphics/dig072.ppm",
    "graphics/dig073.ppm",
    "graphics/dig074.ppm",
    "graphics/dig075.ppm",
    "graphics/dig076.ppm",
    "graphics/dig077.ppm",
    "graphics/dig078.ppm",
    "graphics/dig079.ppm",
    "graphics/dig080.ppm",
    "graphics/dig081.ppm",
    "graphics/dig082.ppm",
    "graphics/dig083.ppm",
    "graphics/dig084.ppm",
    "graphics/dig085.ppm",
    "graphics/dig086.ppm",
    "graphics/dig087.ppm",
    "graphics/dig088.ppm",
    "graphics/dig089.ppm",
    "graphics/dig090.ppm",
    "graphics/dig091.ppm",
    "graphics/dig092.ppm",
    "graphics/dig093.ppm",
    "graphics/dig094.ppm",
    "graphics/dig095.ppm",
    "graphics/dig096.ppm",
    "graphics/dig097.ppm",
    "graphics/dig098.ppm",
    "graphics/dig099.ppm",
    "graphics/dig100.ppm",
    "graphics/dig101.ppm",
    "graphics/dig102.ppm",
    "graphics/dig103.ppm",
    "graphics/dig104.ppm",
    "graphics/dig105.ppm",
    "graphics/dig106.ppm",
    "graphics/dig107.ppm",
    "graphics/dig108.ppm",
    "graphics/dig109.ppm",
    "graphics/dig110.ppm",
    "graphics/dig111.ppm",
    "graphics/dig112.ppm",
    "graphics/dig113.ppm",
    "graphics/dig114.ppm",
    "graphics/dig115.ppm",
    "graphics/dig116.ppm",
    "graphics/dig117.ppm",
    "graphics/dig118.ppm",
    "graphics/dig119.ppm",
    "graphics/dig120.ppm",
    "graphics/dig121.ppm",
    "graphics/dig122.ppm",
    "graphics/dig123.ppm",
    "graphics/dig124.ppm",
    "graphics/dig125.ppm",
    "graphics/dig126.ppm",
    "graphics/fonta06.ppm",
    "graphics/fonta28.ppm",
    "graphics/fonta30.ppm",
    "graphics/boxul.ppm",
    "graphics/boxuc.ppm",
    "graphics/boxur.ppm",
    "graphics/boxcl.ppm",
    "graphics/boxcc.ppm",
    "graphics/boxcr.ppm",
    "graphics/boxll.ppm",
    "graphics/boxlc.ppm",
    "graphics/boxlr.ppm",
    "graphics/stkeys6.ppm",
    "graphics/stkeys7.ppm",
    "graphics/stkeys8.ppm",
    "graphics/stcfn096.ppm",
    "graphics/m_butt1.ppm",
    "graphics/m_butt2.ppm",
    "graphics/m_colors.ppm",
    "graphics/m_palno.ppm",
    "graphics/m_palsel.ppm",
    "graphics/m_vbox.ppm",
    "graphics/cross1.ppm",
    "graphics/cross2.ppm",
    "graphics/cross3.ppm",
    "graphics/cross4.ppm",
    "graphics/cross5.ppm",
    "graphics/cross6.ppm",
    "graphics/cross7.ppm",
};

pub const flats = [_][]const u8{
    "flats/-n0_tex-.ppm",
};

pub const Sprite = struct { x: u16, y: u16, file: []const u8 };

pub const spritep = [_]Sprite{
    .{ .x = 0, .y = 0, .file = "sprites/tnt1a0.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsa1.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsa2.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsa3.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsa4.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsa5.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsa6.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsa7.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsa8.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsb1.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsb2.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsb3.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsb4.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsb5.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsb6.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsb7.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsb8.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsc1.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsc2.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsc3.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsc4.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsc5.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsc6.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsc7.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsc8.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsd1.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsd2.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsd3.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsd4.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsd5.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsd6.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsd7.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsd8.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogse1.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogse2.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogse3.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogse4.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogse5.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogse6.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogse7.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogse8.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsf1.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsf2.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsf3.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsf4.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsf5.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsf6.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsf7.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsf8.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsg1.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsg2.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsg3.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsg4.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsg5.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsg6.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsg7.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsg8.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsh1.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsh2.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsh3.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsh4.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsh5.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsh6.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsh7.ppm" },
    .{ .x = 33, .y = 66, .file = "sprites/dogsh8.ppm" },
    .{ .x = 33, .y = 67, .file = "sprites/dogsi0.ppm" },
    .{ .x = 33, .y = 67, .file = "sprites/dogsj0.ppm" },
    .{ .x = 33, .y = 67, .file = "sprites/dogsk0.ppm" },
    .{ .x = 33, .y = 67, .file = "sprites/dogsl0.ppm" },
    .{ .x = 33, .y = 68, .file = "sprites/dogsm0.ppm" },
    .{ .x = 33, .y = 69, .file = "sprites/dogsn0.ppm" },
    .{ .x = 9, .y = 11, .file = "sprites/pls1a0.ppm" },
    .{ .x = 8, .y = 11, .file = "sprites/pls1b0.ppm" },
    .{ .x = 9, .y = 11, .file = "sprites/pls1c0.ppm" },
    .{ .x = 8, .y = 11, .file = "sprites/pls1d0.ppm" },
    .{ .x = 16, .y = 27, .file = "sprites/pls1e0.ppm" },
    .{ .x = 16, .y = 27, .file = "sprites/pls1f0.ppm" },
    .{ .x = 18, .y = 27, .file = "sprites/pls1g0.ppm" },
    .{ .x = 9, .y = 11, .file = "sprites/pls2a0.ppm" },
    .{ .x = 8, .y = 13, .file = "sprites/pls2b0.ppm" },
    .{ .x = 11, .y = 18, .file = "sprites/pls2c0.ppm" },
    .{ .x = 16, .y = 27, .file = "sprites/pls2d0.ppm" },
    .{ .x = 18, .y = 27, .file = "sprites/pls2e0.ppm" },
};
